// Generated by CIRCT firtool-1.62.0
// VCS coverage exclude_file
module mem_10x20(
  input  [3:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [19:0] R0_data,
  input  [3:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [19:0] W0_data
);

  reg [19:0] Memory[0:9];
  reg        _R0_en_d0;
  reg [3:0]  _R0_addr_d0;
  always @(posedge R0_clk) begin
    _R0_en_d0 <= R0_en;
    _R0_addr_d0 <= R0_addr;
  end // always @(posedge)
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 20'bx;
endmodule

module SRAM(
  input         clock,
                reset,
                io_wea,
  input  [3:0]  io_addra,
  input  [19:0] io_dina,
  output [19:0] io_douta
);

  mem_10x20 mem_ext (
    .R0_addr (io_addra),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (io_douta),
    .W0_addr (io_addra),
    .W0_en   (io_wea),
    .W0_clk  (clock),
    .W0_data (io_dina)
  );
endmodule

